### ISSUE TITLE
Better Exceptions hangs Dask Distributed execution on exception

### ISSUE THREAD

**Issue by frol** [Qix-/better-exceptions#37] opened 2017-05-17 10:31 UTC
Here is the reproduction:

```python
import better_exceptions

import dask
import dask.distributed


def x():
    assert 0

if __name__ == '__main__':
    client = dask.distributed.Client()
    dask.delayed(x)().compute(get=client.get)
```

If I run this code with `import better_exceptions` commented out, I can see the AssertionError traceback and the program exits:

```
$ python test.py
distributed.utils - ERROR -
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/distributed/utils.py", line 212, in f
    result[0] = yield make_coro()
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.5/site-packages/distributed/client.py", line 1551, in _get
    result = yield self._gather(packed)
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.5/site-packages/distributed/client.py", line 996, in _gather
    traceback)
  File "/opt/conda/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "qq3.py", line 8, in x
    assert 0
AssertionError
Traceback (most recent call last):
  File "qq3.py", line 12, in <module>
    dask.delayed(x)().compute(get=client.get)
  File "/opt/conda/lib/python3.5/site-packages/dask/base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/dask/base.py", line 203, in compute
    results = get(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/distributed/client.py", line 1590, in get
    resources=resources)
  File "/opt/conda/lib/python3.5/site-packages/distributed/utils.py", line 223, in sync
    six.reraise(*error[0])
  File "/opt/conda/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/conda/lib/python3.5/site-packages/distributed/utils.py", line 212, in f
    result[0] = yield make_coro()
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.5/site-packages/distributed/client.py", line 1551, in _get
    result = yield self._gather(packed)
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.5/site-packages/distributed/client.py", line 996, in _gather
    traceback)
  File "/opt/conda/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "qq3.py", line 8, in x
    assert 0
AssertionError
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Worker closed
distributed.client - WARNING - Client report stream closed to scheduler
```

However, once I have `import better_exception`, the output is blank and the program just hangs forever.

**Comment by frol** [comment] 2017-06-01 04:47
@Qix- Any ideas? I have just noticed TBVaccine project and its hook works well with Dask Distributed...

@skorokithakis Thank you for mentioning TBVaccine! It works great for me where better-exceptions just breaks things.

**Comment by Qix-** [comment] 2017-06-01 06:11
Might be an endless loop while formatting. I'm going to be pretty busy the next few weeks but will try to take a look for you.

Thank you for the repro case, that's super helpful :)

**Comment by Delgan** [comment] 2017-09-05 17:31
@frol Hi!

I wanted to work on this issue but unfortunately I can not reproduce the error.
Are you still able to reproduce it?

If so, some information about your configuration may be usefull: distribution, libraries versions (run `pip freeze`), python version (run `python --version`).

I have studied the source code a bit and I do not see where there could be an infinite loop.

Sometimes your snippet takes a long time to run but the error always appears in the end (although I do not see any logging messages), with or without `better_exceptions` imported.

**Comment by frol** [comment] 2017-09-05 18:05
@Delgan Either `dask` or `distributed` has changed something so it works fine now with the latest versions of those. Downgrading `pip install dask==0.14.3 distributed==1.16.1` makes the issue reproducible.

**Comment by Delgan** [comment] 2017-09-05 21:41
@frol Indeed, I can reproduce the error now, thank you!

**Comment by Delgan** [comment] 2017-09-06 18:17
So, `better_exceptions` is hanging [here](https://github.com/Qix-/better-exceptions/blob/0.1.8/better_exceptions/__init__.py#L154).

Prepend the `format_value` function with:

```python
if getattr(v, '__name__', None) == '_get':
    help(v)
    print("The program will crash...")
print("v =", v)
```

And then...
![1504718117-screenshot](https://user-images.githubusercontent.com/4193924/30125175-dcd36a0e-9337-11e7-8789-3536ece6de50.png)

Strangely, it is not possible to display the method.

My traceback is slightly different from yours.
The first line is `result[0] = yield gen.maybe_future(func(*args, **kwargs))`.
It appears that this [`func`](https://github.com/dask/distributed/blob/1.16.1/distributed/utils.py#L193) function is actually the [`_get`](https://github.com/dask/distributed/blob/1.16.1/distributed/client.py#L1479) method which cannot be displayed.
This is why it prevents `better_exceptions` to format the traceback.
The function [`make_coro`](https://github.com/dask/distributed/blob/1.16.2/distributed/utils.py#L188) of your traceback appears with v1.16.3 and uses `func` too.
There is no error with TBVaccine because it does not introspect this traceback.

I then tried to study the code of `distributed` but wow... It is a little  bit too complex for me.
It is perhaps related to this [`__str__`](https://github.com/dask/distributed/blob/1.16.1/distributed/client.py#L391-L401) function.
In the end, it looks like the bug came from `distributed` and not `better_exceptions`.
The bug stopped occurring with [v1.17.0](https://github.com/dask/distributed/blob/master/docs/source/changelog.rst#1170---june-9th-2017) when they removed the `_get` function.
However, I am not sure that the bug has completely disappeared.
Maybe it has just been moved, and that the snippet here does not show it anymore.

**Comment by Qix-** [comment] 2019-01-14 14:39
I hold pretty firm with the idea that performing any I/O in `__str__` or `__repr__` is an anti-pattern and definitely not a use-case we should bend over backwards for.

Sounds like it got resolved in a successive release - going to close. Let me know if this is still a problem for anyone.

**Closed by Qix-** 2019-01-14 14:39 UTC
