### ISSUE TITLE
Merge with TBVaccine?

### ISSUE THREAD

**Issue by skorokithakis** [Qix-/better-exceptions#38] opened 2017-05-18 12:01 UTC
Hello, I'm the author of [tbvaccine](https://github.com/skorokithakis/tbvaccine/), which is very similar in functionality. I just discovered this library, and quite like how variables are presented (tbvaccine prints all the locals in the frame).

Would you consider merging the two, or implementing some features so tbvaccine is superseded? Mainly, the features are highlighting the parts of the traceback that are relevant to the user (see screenshots), making the filenames bold, etc.

Thanks!

**Comment by Qix-** [comment] 2017-05-18 18:47
I'd be interested in seeing what the exception looked like when the irrelevant bits are dimmed instead - however I'm not sure what TVVaccine does that's much different from this module :o

I can definitely make the filenames bold, however.

**Comment by frol** [comment] 2017-06-01 05:01
Just my 2 cents, I like TBVaccine's way of registering a global hook explicitly with `add_hook` (I understand that it is one extra line in the usage, but I still like the explicit and configurable way better)

**Comment by Qix-** [comment] 2017-09-13 07:15
The case against it @frol is that this kind of hack to help you debug shouldn't necessarily be application specific. It should be applicable to any python script that temporarily wants to show debug information for convoluted stack traces.

Encouraging users to include the hook in their scripts only encourages security and privacy vectors to be created. I'm actually glad @paradoxxxzero created his automatic hook module since I think it's a superior way to load this module and I've considered merging the two.

cc @Delgan

**Comment by Delgan** [comment] 2017-09-13 07:26
@Qix- We can also do `import better_exceptions.auto` for an automatic hook, and those who prefer to add it manually can do `import better_exceptions; better_exceptions.add_hook()`.

With the commit I just merged, they could also do `import better_exceptions_core; better_exceptions_core.add_hook()`.

Personally, I find the `import better_exceptions.auto` much more elegant, the problem is that it breaks the compatibility with the previous version if `import better_exceptions` no longer add an automatic hook.

**Comment by Delgan** [comment] 2017-09-14 18:17
So, I guess we can merge the @paradoxxxzero's automatic hook using the @anntzer solution: https://github.com/qix-/better-exceptions/issues/24#issuecomment-306714896

That way, `better_exceptions` can work without any import (which makes sense as one usually want enhanced exceptions everywhere).

Moreover, a better control can be achieved as requested by @frol by setting the `BETTER_EXCEPTIONS` environment variable to `False` and manually `import better_exceptions; better_exceptions.hook()`. This will allow implementing #40 without my `better_exceptions_core` workaround, as `import better_exceptions` will no longer automatically hook.

@Qix-  So, quick question: do you want `pip install better_exceptions` to automatically set the environment variable to `True` (I guess the `setup.py` can be modified to perform a post-install action)? Or should we let it unset and instead indicate in the README how to enable it?

**Comment by Qix-** [comment] 2017-09-14 20:26
Great questions.

To me, `better_exceptions` should never touch code. After writing it enough, I feel like it'll be misused or (worse) used in a library, making unexpected side effects for consumers of that library.

I've had a disclaimer in there before that it should _only_ be used in debugging/local/dev/staging environments, as there is no way to filter out sensitive information from the traces and thus might expose sensitive information in logs if used incorrectly.

I think @paradoxxxzero was exactly right with his module.

**Comment by Qix-** [comment] 2019-01-14 14:36
This is effectively a duplicate of #51 - sorry for the lapse in action here, @skorokithakis.

I plan on getting #51 out the door at some point, so if that's all that is necessary to succeed tbvaccine then I'm :+1: on this. :) @Delgan has been a massive help in maintaining this module and I don't see it dying any time soon. We just signed the python 3 initiative w.r.t. dropping support for python 2 starting no later than Jan 1, 2020.

**Comment by skorokithakis** [comment] 2019-01-14 15:01
No problem, @Qix-. In the mean time, TBVaccine got stack variable printing and various other features which enhanced it, so I think it's currently on par or better than `better-exceptions`, making this issue a bit moot. We could still merge, just to avoid having two libraries that do the same thing, but it's not that urgent (and I don't know if it makes much sense given the different codebases).

**Comment by Qix-** [comment] 2019-01-14 15:13
No problem, we'll go ahead and close this then :) Users can decide.

Thanks again for reaching out @skorokithakis 😃

**Comment by skorokithakis** [comment] 2019-01-14 15:14
Thank you!

**Closed by Qix-** 2019-01-14 15:13 UTC
Labels: question
